#!/bin/bash

#	DOPLNIT!
#	1. Pri spusteni klienta alebo servera vypisat vysvetlivky
#	
#
#
##############################################################

#       Premene
nickname=""
port1=0
port2=0
vyber_mozn=10
localhost=localhost

name_server=./Server
name_klient=./Klient

function pmenu_hl() {
	clear
	echo "---------===MENU===---------"
	echo "<1>------Spustenie Serveru--"
	echo "<2>------Spustenie Klienta--"
	echo "<3>------Informacie---------"
	echo "<0>------Ukoncit applikaciu-"
	echo "---------==========---------"
	read -p "---Vasa volba: " vol
	return $vol
}

function pmenu_info() {
        clear
        echo "---------===INFORMACIE===---------"
        echo "<1>------Zdrojovy kod: Serveru----"
        echo "<2>------Zdrojovy kod: Klientu----"
        echo "<0>------Navrat do hl.Menu--------"
        echo "---------================---------"
        read -p "---Vasa volba: " vol
        
        if [[ $vol == "1" ]]
        then
        	cat Server.c
        	echo ""
        	read -p "---Pre ukoncenie stlacte Enter: " vol
        fi       
        
        if [[ $vol == "2" ]]
        then
                cat Klient.c
                echo ""
                read -p "---Pre ukoncenie stlacte Enter: " vol
        fi

}

function pmenu_server() {
	clear
	echo "---------===Spustenie Serveru===---------"
        read -p "---Zadajte cislo portu1: " port1
        read -p "---Zadajte cislo portu2: " port2
        echo "<1>------Spustenie server: Port1: $port1"
        echo "                           Port2: $port2"
        echo "<0>------Navrat do hl.Menu---------------"
        echo "---------=======================---------"
        read -p "---Vasa volba: " vol
        return $vol
}

function pmenu_klient() {
        clear
        echo "---------===Spustenie Klienta===---------"
        read -p "---Zadajte port1 serveru: " port1
        read -p "---Zadajte port2 serveru " port2
        echo "<1>------Spustenie klienta: Nickname: $nickname"
        echo "                                Port1: $port1"
        echo "                                Port2: $port2"
        echo "<0>------Navrat do hl.Menu---------------"
        echo "---------=======================---------"
        read -p "---Vasa volba: " vol
        return $vol
}



while [[ true ]]
do
	#	"HL.MENU"
	pmenu_hl			
	#	Volba
	case $? in
			
		1) #	"SERVER"
		pmenu_server
		if [[ $? == "1" ]]
		then
			clear
			echo "---SERVER---"
#			$name_server echo "$port1" "$port2"
			$name_server "$port1" "$port2"

			break
		fi
		;;
		
		2) #	"KLIENT"
		pmenu_klient
		if [[ $? == "1" ]]
                then
                	clear
                        echo "---KLIENT---"
                        $name_klient "$localhost" "$port1" "$port2"
                        #$name_klient echo "localhost $port1 $port2"
                	break
                fi
		;;
		
		3) #	"INFORMACIE"
			pmenu_info
		;;
		
		0) # 	"EXIT"
		break
		;;		
		
	 	*) #	"UNKNOWN"
	 	;;
	
	esac	
done

echo "Aplikacia bola ukoncena"

































